### ISSUE TITLE
Review with negative words not predicted accurately

### ISSUE THREAD

**Issue by ManasviEmmadi** [jasmine1601/Sentiment-Analysis-using-SVM#10]
@jasmine1601 hey if I give a review like "I don't like it", it still predicts as a positive review. I could work on this issue.

**Comment by jasmine1601** [comment]
@ManasviEmmadi Please follow the issue template and don't remove the existing issue template while typing :)
Also, do join the Gitter channel and tell me what changes will you make to solve the problem you mentioned.
